//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APLICACIONBARRON2.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APLICACIONBARRON2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _28_asombrosos_fondos_diapositivas_Power_Point_que_puedes_descargar_gratis {
            get {
                object obj = ResourceManager.GetObject("28 asombrosos fondos diapositivas Power Point que puedes descargar gratis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Agregar_Doc___Icono {
            get {
                object obj = ResourceManager.GetObject("Agregar Doc _ Icono", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cerrar__borrar__eliminar_el_icono_cuadrado___Icono_Gratis {
            get {
                object obj = ResourceManager.GetObject("Cerrar, borrar, eliminar el icono cuadrado _ Icono Gratis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap descarga {
            get {
                object obj = ResourceManager.GetObject("descarga", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap descarga__1_ {
            get {
                object obj = ResourceManager.GetObject("descarga (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap descarga__2_ {
            get {
                object obj = ResourceManager.GetObject("descarga (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap descarga__3_ {
            get {
                object obj = ResourceManager.GetObject("descarga (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap descarga__3_1 {
            get {
                object obj = ResourceManager.GetObject("descarga (3)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Descargar_icono_de_perfil_de_usuario_gratis {
            get {
                object obj = ResourceManager.GetObject("Descargar icono de perfil de usuario gratis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Download_premium_vector_of_Dark_tone_Memphis_Instagram_ad_background_vector_by_Wan_about_dark_tone_memphis_instagram_background__pattern__aesthetic_template_background__aesthetic_powerpoint__and_memphis_2210929 {
            get {
                object obj = ResourceManager.GetObject("Download premium vector of Dark tone Memphis Instagram ad background vector by Wa" +
                        "n about dark tone memphis instagram background, pattern, aesthetic template back" +
                        "ground, aesthetic powerpoint, and memphis 2210929", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Eliminar___Icono {
            get {
                object obj = ResourceManager.GetObject("Eliminar _ Icono", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icono_De_Candado_Diseño_Plantilla_Vector_Isolated_PNG___Imágenes_Prediseñadas_De_Candado__Iconos_De_Plantilla__Iconos_De_Candado_PNG_y_Vector_para_Descargar_Gratis___Pngtree {
            get {
                object obj = ResourceManager.GetObject("Icono De Candado Diseño Plantilla Vector Isolated PNG , Imágenes Prediseñadas De " +
                        "Candado, Iconos De Plantilla, Iconos De Candado PNG y Vector para Descargar Grat" +
                        "is _ Pngtree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icono_De_Candado_Diseño_Plantilla_Vector_Isolated_PNG___Imágenes_Prediseñadas_De_Candado__Iconos_De_Plantilla__Iconos_De_Candado_PNG_y_Vector_para_Descargar_Gratis___Pngtree1 {
            get {
                object obj = ResourceManager.GetObject("Icono De Candado Diseño Plantilla Vector Isolated PNG , Imágenes Prediseñadas De " +
                        "Candado, Iconos De Plantilla, Iconos De Candado PNG y Vector para Descargar Grat" +
                        "is _ Pngtree1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Iconos_de_Editar_Documento_para_descargar_gratis {
            get {
                object obj = ResourceManager.GetObject("Iconos de Editar Documento para descargar gratis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Iconos_de_Salir_Al_Boton_Aplicacion_para_descargar_gratis {
            get {
                object obj = ResourceManager.GetObject("Iconos de Salir Al Boton Aplicacion para descargar gratis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Iconos_de_Salir_Al_Boton_Aplicacion_para_descargar_gratis1 {
            get {
                object obj = ResourceManager.GetObject("Iconos de Salir Al Boton Aplicacion para descargar gratis1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Premium_Vector___Welcome_brush_lettering___illustration_for_decoration_or_banner_slogan {
            get {
                object obj = ResourceManager.GetObject("Premium Vector _ Welcome brush lettering_  illustration for decoration or banner " +
                        "slogan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Starting_from_scratch {
            get {
                object obj = ResourceManager.GetObject("Starting from scratch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Welcome_Letter_Clipart_Vector__Welcome_Text_Hand_Lettering_With_Flowers_And_Hearts_Of_Love__Welcome__Welcome_Home__Welcome_Baby_Girl_PNG_Image_For_Free_Download {
            get {
                object obj = ResourceManager.GetObject("Welcome Letter Clipart Vector, Welcome Text Hand Lettering With Flowers And Heart" +
                        "s Of Love, Welcome, Welcome Home, Welcome Baby Girl PNG Image For Free Download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Welcome_Letter_Vector_Hd_PNG_Images__Welcome_Text_Hand_Lettering_With_Flowers_And_Leaves_Decoration_Letters__Welcome_Back_Clipart__Welcome__Welcome_Home_PNG_Image_For_Free_Download {
            get {
                object obj = ResourceManager.GetObject("Welcome Letter Vector Hd PNG Images, Welcome Text Hand Lettering With Flowers And" +
                        " Leaves Decoration Letters, Welcome Back Clipart, Welcome, Welcome Home PNG Imag" +
                        "e For Free Download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap من_ايقونة__مشكلة_مشكلة__أيقونة__من_PNG_والمتجهات_للتحميل_مجانا {
            get {
                object obj = ResourceManager.GetObject("من ايقونة, مشكلة مشكلة, أيقونة, من PNG والمتجهات للتحميل مجانا", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
